### ISSUE TITLE
increase uwsgi processes

### ISSUE THREAD

**Issue by Dirowa** [Avans-ATGM/infrastructure#21]
hi @hexylena,

I was working wih Bazante to guide a few students on our galaxy server.
I did hold a watch on our server by grafana and I noticed that there were some jobs in queue (my jobs didn't require previous calculations) where the CPU and ram usage where quite low.

is it maybe an idea to increase the number of uwsgi workers?

**Comment by hexylena** [comment]
uwsgi workers won't change how many jobs are run simultaneously. That's due to:

- registered_user_concurrent_jobs">8 - this is used to prevent one user taking over the entire server and ensure QoS for everyone during e.g. courses. 
- individual tools regiser their memory/cpu needs - if the tools are using significantly less memory/cpu than we schedule them for, we should think about how to fix that. It's a tough problem in e.g. EU since we want jobs to succeed and not crash with out of memory errors so we don't want to make it too small, and we want to run many jobs simultaneously, so we don't want to make it too large.

Did you see why the jobs weren't being run? Too many simultaneous jobs currently?

**Comment by Dirowa** [comment]
yes, thank you for the exstra explaination.
but uhm, is the HTcondor other VM's taken into account in that?, because I see that one isn't used.

maybe something for me to investigate?
